### ISSUE TITLE
WCActionSheet's UIWindow pass touches to underlying view 

### ISSUE THREAD

**Issue by slxl** [wokalski/WCActionSheet#5]
In my case I was able to touch a cancel button on navigation bar (but other underlying UI elements were inaccessible).

Using 
   ``` [window makeKeyAndVisible];```
instead of
    ```window.hidden = NO;```
solves the problem

**Comment by wczekalski** [comment]
Good find. Could you submit a pull request with your change?

**Comment by slxl** [comment]
@wczekalski done.
